name: Deploy

on:
  push:
    branches:
      - main

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Secret value
        run: echo "Secret value is ${{ secrets.TOKEN_SECRET }}"

      - name: setup
        uses: actions/setup-node@v4
        with:
          node-version: '18'